[package]
name = "message-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.11", features = ["toml"] }
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
tracing = { version = "0.1.41" }
